name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Test with Gradle # test application build
        run: ./gradlew test
        
      - name: Build with Gradle
        run: ./gradlew build -x test
        
#       - name: Temporarily save build artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: build-artifact
#           path: build
#           retention-days: 1
 
